version: 2
jobs:
  publish:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew clean fatJar publish
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: 
                - vinod-1-patch-2 
