version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - m2-
  publish:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew clean fatJar publish
 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - publish:
          requires:
            - build
