version: 2
jobs:
  publish:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew clean fatJar publish
 
workflows:
  version: 2
      - publish
          filters
            branches
              only: 
                - master #Change or Update whatever branch needs to be published
